# Generated by Django 5.0.1 on 2024-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
