# Generated by Django 5.0.1 on 2024-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_user.jpg', upload_to='user-images/'),
        ),
    ]
