# Generated by Django 5.0.1 on 2024-02-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(choices=[('path1', 'Path 1'), ('path2', 'Path 2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(choices=[('company1', 'Company 1'), ('company2', 'Company 2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventsAndWorkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('EventTime', models.TimeField()),
                ('Eventplace', models.CharField(max_length=100)),
                ('EventPath', models.ManyToManyField(related_name='EventsAndWorkshops', to='Server.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('Path', models.ManyToManyField(related_name='Courses', to='Server.careerpath')),
                ('RelatedEvents', models.ManyToManyField(blank=True, related_name='Courses', to='Server.eventsandworkshops')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainingName', models.CharField(max_length=100)),
                ('TrainingTime', models.TimeField()),
                ('TrainingPlace', models.CharField(max_length=100)),
                ('TrainingCompany', models.ManyToManyField(blank=True, null=True, related_name='Training', to='Server.company')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=100)),
                ('JobDiscribtion', models.TextField()),
                ('JobAssociations', models.ManyToManyField(to='Server.careerpath')),
                ('JobTraining', models.ManyToManyField(to='Server.training')),
            ],
        ),
    ]
