# Generated by Django 5.0.1 on 2024-02-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpath',
            old_name='CompanyName',
            new_name='Paths',
        ),
    ]
