# Generated by Django 5.0.1 on 2024-02-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_rename_companyname_careerpath_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='TrainingCompany',
            field=models.ManyToManyField(blank=True, related_name='Training', to='Server.company'),
        ),
    ]
