# Generated by Django 5.0.1 on 2024-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_alter_training_trainingcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='Paths',
            field=models.CharField(max_length=50),
        ),
    ]
