# Generated by Django 5.0.1 on 2024-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_alter_careerpath_paths_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
