# Generated by Django 5.0.1 on 2024-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career_path_images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, default='zero', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='eventsandworkshops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_images/'),
        ),
    ]
