# Generated by Django 5.0.1 on 2024-06-14 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_careerpath_image_company_image_course_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='eventsandworkshops',
            old_name='event',
            new_name='Event',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='https://www.youtube.com/watch?v=4sYNBViSq-8', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventsandworkshops',
            name='Deadline',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandworkshops',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 14, 57, 34, 410777)),
        ),
        migrations.AddField(
            model_name='eventsandworkshops',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='training',
            name='TrainingDate',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 14, 57, 34, 410777)),
        ),
        migrations.AlterField(
            model_name='eventsandworkshops',
            name='EventTime',
            field=models.TimeField(default=datetime.datetime(2024, 6, 14, 14, 57, 34, 410777)),
        ),
        migrations.AlterField(
            model_name='training',
            name='TrainingTime',
            field=models.TimeField(default=datetime.datetime(2024, 6, 14, 14, 57, 34, 410777)),
        ),
    ]
