# Generated by Django 5.0.1 on 2024-06-14 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_roadmap_rename_event_eventsandworkshops_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandworkshops',
            name='EventDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventsandworkshops',
            name='EventTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='TrainingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='TrainingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
