# Generated by Django 5.0.1 on 2024-06-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_alter_eventsandworkshops_eventdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsandworkshops',
            old_name='Event',
            new_name='event',
        ),
    ]
