# Generated by Django 5.0.1 on 2024-06-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0010_rename_event_eventsandworkshops_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_steps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FourthSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourth_steps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_steps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_steps', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='Server.careerpath'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='first_steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstSteps', to='Server.firststeps'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='fourth_steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourtSteps', to='Server.fourthsteps'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='second_steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondSteps', to='Server.secondsteps'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='third_steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdSteps', to='Server.thirdsteps'),
        ),
    ]
