# Generated by Django 5.0.1 on 2024-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0011_firststeps_fourthsteps_secondsteps_thirdsteps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='describition',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='Paths',
            field=models.CharField(choices=[('Penetraion Testing', 'penetraion testing'), ('Blue Teaming', 'blue teaming'), ('Red Teaming', 'blue teaming')], max_length=50),
        ),
    ]
