# Generated by Django 5.0.1 on 2024-06-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0014_remove_roadmap_first_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='Server.careerpath'),
        ),
    ]
